// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlgNltx2WR1yC8XAACvZw04QHVeKNFb8',
    appId: '1:191648214263:ios:0a94bca14e6820e593b7f2',
    messagingSenderId: '191648214263',
    projectId: 'ios-live-cricket-score-tv',
    storageBucket: 'ios-live-cricket-score-tv.firebasestorage.app',
    iosBundleId: 'com.aryatech.cricketlivescore',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVS-ZjGhctIRrzpkzlqd8x0lb9URZq-oo',
    appId: '1:191648214263:android:d5c4ef56b7255cbd93b7f2',
    messagingSenderId: '191648214263',
    projectId: 'ios-live-cricket-score-tv',
    storageBucket: 'ios-live-cricket-score-tv.firebasestorage.app',
  );

}